#!/usr/bin/env python3.8

# 1:  < ZWAXJGDLUBVIQHKYPNTCRMOSFE <
# 2:  < KPBELNACZDTRXMJQOYHGVSFUWI <
# 3:  < BDMAIZVRNSJUWFHTEQGYXPLOCK <
# 4:  < RPLNDVHGFCUKTEBSXQYIZMJWAO <
# 5:  < IHFRLABEUOTSGJVDKCPMNZQWXY <
# 6:  < AMKGHIWPNYCJBFZDRUSLOQXVET <
# 7:  < GWTHSPYBXIZULVKMRAFDCEONJQ <
# 8:  < NOZUTWDCVRJLXKISEFAPMYGHBQ <
# 9:  < XPLTDSRFHENYVUBMCQWAOIKZGJ <
# 10: < UDNAJFBOWTGVRSCZQKELMXYIHP <
# 11： < MNBVCXZQWERTPOIUYALSKDJFHG <
# 12： < LVNCMXZPQOWEIURYTASBKJDFHG <
# 13： < JZQAWSXCDERFVBGTYHNUMKILOP <
# 
# 密钥为：2,3,7,5,13,12,9,1,8,10,4,11,6
# 密文为：NFQKSEVOQOFNP

rows = [
        "ZWAXJGDLUBVIQHKYPNTCRMOSFE",
        "KPBELNACZDTRXMJQOYHGVSFUWI",
        "BDMAIZVRNSJUWFHTEQGYXPLOCK",
        "RPLNDVHGFCUKTEBSXQYIZMJWAO",
        "IHFRLABEUOTSGJVDKCPMNZQWXY",
        "AMKGHIWPNYCJBFZDRUSLOQXVET",
        "GWTHSPYBXIZULVKMRAFDCEONJQ",
        "NOZUTWDCVRJLXKISEFAPMYGHBQ",
        "XPLTDSRFHENYVUBMCQWAOIKZGJ",
        "UDNAJFBOWTGVRSCZQKELMXYIHP",
        "MNBVCXZQWERTPOIUYALSKDJFHG",
        "LVNCMXZPQOWEIURYTASBKJDFHG",
        "JZQAWSXCDERFVBGTYHNUMKILOP"
       ]

keys = [2, 3, 7, 5, 13, 12, 9, 1, 8, 10, 4, 11, 6]
ct = "NFQKSEVOQOFNP"

def rotate(row, num):
    return row[num:] + row[:num]

for i, row_key in enumerate(keys):
    ct_row = rows[row_key-1]
    ct_char = ct[i]
    # Unshift the row
    while ct_row[0] != ct_char:
        ct_row = rotate(ct_row, 1)
    print(''.join([x+"   | " for x in ct_row]))
