#!/usr/bin/env python3

import binascii

with open('pooh_hex.jpg', 'r') as infile:
    # pooh_hex generated by:
    # (After fixing the header by taking the last line at the end of the file
    # and placing it at:
    #     00000120: ffd8 ffe0 0010 4a46 4946 0001 0101 012c
    # cat pooh.jpg | awk '{print $2 $3 $4 $5 $6 $7 $8 $9}' | pbcopy
    hex_string=''.join(infile.read().split('\n'))

data = binascii.a2b_hex(hex_string)
with open('pooh_reconstructed.jpg', 'wb') as image_file:
    image_file.write(data)
    # castorsCTF{H3r3_Is_y0uR_Fl4gg}
